name: Lint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      # Node versions list
      matrix:
        node-version: [14.x]

    steps:
      - name: make install
        run: name install
      - name: lint
        run: make lint

